### ISSUE TITLE
| - "filter symbol" must be without spaces around it

### ISSUE THREAD

**Issue by divined** [mblode/vscode-twig-language-2#23]
{{ some_array|length  }}
and not
{{ some_array | length  }}

**Comment by thomasfrobieter** [comment]
I've experienced this issue also in the past, but this seems fixed? Works for me.

**Comment by thomasfrobieter** [comment]
Okay, now it's happened again. 

`{{ rendercontent['field_image_caption']|field_value }}`
works

`{% set link_label = 'read on'|t %}`
works not:
`{% set link_label = 'read on' | t %}`

So .. i need to disable the Twig formatter again because the code is getting destroyed..  working many months without working Twig support in VScode :'(

**Comment by mblode** [comment]
0.12.0 preserves Twig filter expressions without rewriting the pipe spacing. Added regression coverage for these cases.
