### ISSUE TITLE
Twig Language 2 lowercase / CamelCase

### ISSUE THREAD

**Issue by heyhey-daan** [mblode/vscode-twig-language-2#26]
Hey There,

Great plugin!

I've encountered a problem which I didn't know how to fix fast. Maybe if I have some more time I will try to find a solution. Im using Twig Language 2 with VScode Prettier. For some reason when I save a file ( with format on save enabled ) it makes all camelcase svg lowercase. When I disable Twig Language 2 and save Prettier does not make the HTML lowercase. 

This causes an issue when animating with javascript.

**Current behaviour**
Input:
`<svg viewBox=0 0 800 600"></svg>`
Output:
`<svg viewbox=0 0 800 600"></svg>`

**Expected behaviour**
Input:
`<svg viewBox=0 0 800 600"></svg>`
Output:
`<svg viewBox=0 0 800 600"></svg>`

This is for all related svg tags such as filter and

**Comment by heyhey-daan** [comment]
Dear reader,
HeyHeydeHaas is closed for the Holidays.

This email will not be forwarded. I will respond to your message when I return on January 2.

Kindest Regards,
Daan Spanjers

HeyHeydeHaas

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

HALLENWEG 2A
5615 PP EINDHOVEN
T: +31 6 28 47 45 07‬

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mblode** [comment]
Hey @heyhey-daan, I have just pushed an update to Twig Language 2 with a brand new formatter using Prettydiff 3 which brings about some major bug fixes. This bug has now been fixed in the newest version of the extension. Sorry about the slow development speeds and sub-par communication but hopefully these updates have fixed some of your other problems.

**Comment by mblode** [comment]
Fixed in 0.12.0. Formatting preserves attribute case, including SVG viewBox.
